# Configuration file to set arguments for GCsnap.
# To change argument, change: value: entry.
# E.g. value: 1 to value: 2
# ---------------------------------------
# 
out-label:
    value: default
    type: str
    help: Name of output directory. If default, name of the input file.
tmp-mmseqs-folder:
    value:
    type: str
    help: The temporary folder to store mmseqs files. May be changed so that intermediary
        mmseqs files are saved somewhere else then the automatic 'out-label' directory.
collect-only:
    value: false
    type: bool
    help: Boolean statement to make GCsnap collect genomic contexts only, without
        comparing them.
n-cpu:
    value: 4
    type: int
    help: Number of cores to use.
clans-patterns:
    value:
    type: str
    help: Patterns to identify the clusters to analyse. They will be used to select
        the individual clusters in the clans map to analyse.
clans-file:
    value:
    type: str
    help: Used only for advanced interactive output representation (Clans file if
        the input is a clans file and -operon_cluster_advanced is set to True).
ncbi-user-email:
    value:
    type: str
    help: Email address of the user. May be required to access NCBI databases and
        is not used for anything else.
ncbi-api-key:
    value:
    type: str
    help: The key for NCBI API, which allows for up to 10 queries per second to NCBI
        databases. Shall be obtained after obtaining an NCBI account.
n-flanking5:
    value: 4
    type: int
    help: Number of flanking sequences to take on 5' end.
n-flanking3:
    value: 4
    type: int
    help: Number of flanking sequences to take on 3' end.
exclude-partial:
    value: true
    type: bool
    help: Exclude partial operon/genomic_context blocks. If turned off, partial cases
        will still be ignored to get the most common genomic features.
max-evalue:
    value: 0.001
    type: float
    help: Max e-value at which two sequences are considered to be homologous. Required
        to define protein families.
default-base:
    value: 10
    type: int
    help: Artificial distance value for two sequences that do not match with an E-value
        better than --max-evalue.
min-coverage:
    value: 0.7
    type: float
    help: Minimum coverage of target and subject a match needs to be so that two sequences
        are considered to be homologous. Required to define protein families.
num-iterations:
    value: 1
    type: int
    help: Number of iterations for all-against-all searches. Required to define protein
        families.
mmseqs-executable-path:
    value: C:\MT\GCsnap\mmseqs-win64\mmseqs\mmseqs.bat
    type: str
    help: Path of MMseqs executable (i.e., mmseqs.bat) if not installed in Conda environment.
get-pdb:
    value: true
    type: bool
    help: Get PDB information for representatives of the families found.
get-functional-annotations:
    value: true
    type: bool
    help: Find functional annotations for representatives of the families found.
operon-cluster-advanced:
    value: false
    type: bool
    help: Boolean statement to use the operon clustering advanced mode using PacMAP.
max-family-freq:
    value: 20
    type: int
    help: Maximum frequency of a family in the set of genomic contexts found to be
        considered for advanced operon clustering.
min-family-freq:
    value: 2
    type: int
    help: Minimum frequency of a family in the set of genomic contexts found to be
        considered for advanced operon clustering.
min-family-freq-accross-contexts:
    value: 30
    type: int
    help: Minimum frequency of a family in a conserved genomic context type to be
        considered as a member.
n-max-operons:
    value: 30
    type: int
    help: Maximum number of top most populated operon/genomic_context block types.
get-taxonomy:
    value: true
    type: bool
    help: Boolean statement to get and map taxonomy information.
annotate-TM:
    value: true
    type: bool
    help: Boolean statement to find sequence features in the flanking genes.
annotation-TM-mode:
    value: uniprot
    type: str
    help: Method to use to find transmembrane segments.
    choices:
      - phobius
      - tmhmm
      - uniprot
annotation-TM-file:
    value:
    type: str
    help: File with pre-computed transmembrane features. Only use when the targets
        correspond to a single project (no multiple fasta or text files).
interactive:
    value: true
    type: bool
    help: Boolean statement to make the interactive html output.
genomic-context-cmap:
    value: Spectral
    type: str
    help: Color map (as of matplotlib) to assign colors to and plot the syntenic blocks.
gc-legend-mode:
    value: species
    type: str
    help: Mode of the genomic context legend.
    choices:
      - species
      - ncbi_code
out-format:
    value: png
    type: str
    help: Output format of the core figures.
    choices:
      - png
      - svg
      - pdf
min-coocc:
    value: 0.3
    type: float
    help: Minimum maximum co-occurrence of two genes to be connected in the graphs.
in-tree:
    value:
    type: str
    help: Input phylogenetic tree. Only use when the targets correspond to a single
        project (no multiple fasta or text files).
in-tree-format:
    value: newick
    type: str
    help: Format of the input phylogenetic tree.
    choices:
      - newick
      - nexus
      - phyloxml
      - phyloxml-strict
      - phyloxml-extended
      - phyloxml-complete
sort-mode:
    value: taxonomy
    type: str
    help: Mode to sort the genomic contexts.
    choices:
      - taxonomy
      - as_input
      - tree
      - operon
      - operon cluster
overwrite-config:
    value: false
    type: bool
    help: Overwrite the argument value in config file with CLI value.
